### ISSUE TITLE
other branding path

### ISSUE THREAD

**Issue by denis-gorin** [graham73may/bolt-ajax-multi-contenttype-select-field#2]
`return '/bolt/ajax-multi-ct-select?page=' + page;`

so, if I hav other branding path than bolt?

**Comment by graham73may** [comment]
Do you have any examples of this in other plugins? TBH I'm not quite sure what the "correct" way to deal with this is.

**Comment by denis-gorin** [comment]
me too
may be not to place url  in js file, but get path from config and put it in the twig template (thru data attr of an element), then get it in js... long way, but I don'have another idea

**Comment by JarJak** [comment]
@graham73may what @denis-gorin proposed is a correct way :)

**Comment by graham73may** [comment]
Done! :-)
